"""add symptoms, choice stroke

Revision ID: 8560e0486b6a
Revises: 2e83be530376
Create Date: 2026-10-05 06:58:07.424252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8560e0486b6a'
down_revision: Union[str, Sequence[str], None] = '2e83be530376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('symptoms', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.execute("ALTER TYPE stroke ADD VALUE IF NOT EXISTS 'choice'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'symptoms')
    # ### end Alembic commands ###
